// @ts-nocheck
import * as __fd_glob_68 from "../content/docs/index.fa.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/index.en.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/index.de.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/easify-validation.fa.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/easify-validation.en.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/easify-validation.de.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/easify-ui.fa.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/easify-ui.en.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/easify-ui.de.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/easify-storage.fa.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/easify-storage.en.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/easify-storage.de.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/easify-sensor.fa.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/easify-sensor.en.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/easify-sensor.de.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/easify-security.fa.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/easify-security.en.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/easify-security.de.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/easify-persian.fa.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/easify-persian.en.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/easify-persian.de.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/easify-permission.fa.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/easify-permission.en.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/easify-permission.de.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/easify-notification.fa.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/easify-notification.en.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/easify-notification.de.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/easify-network.fa.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/easify-network.en.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/easify-network.de.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/easify-location.fa.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/easify-location.en.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/easify-location.de.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/easify-lifecycle.fa.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/easify-lifecycle.en.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/easify-lifecycle.de.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/easify-image.fa.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/easify-image.en.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/easify-image.de.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/easify-haptic.fa.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/easify-haptic.en.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/easify-haptic.de.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/easify-format.fa.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/easify-format.en.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/easify-format.de.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/easify-form.fa.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/easify-form.en.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/easify-form.de.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/easify-fintech.fa.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/easify-fintech.en.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/easify-fintech.de.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/easify-file.fa.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/easify-file.en.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/easify-file.de.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/easify-context.fa.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/easify-context.en.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/easify-context.de.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/easify-camera.fa.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/easify-camera.en.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/easify-camera.de.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/easify-bluetooth.fa.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/easify-bluetooth.en.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/easify-bluetooth.de.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/easify-biometric.fa.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/easify-biometric.en.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/easify-biometric.de.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/easify-android.fa.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/easify-android.en.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/easify-android.de.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();

export const docs = await create.doc("docs", "content/docs", {"easify-android.de.mdx": __fd_glob_0, "easify-android.en.mdx": __fd_glob_1, "easify-android.fa.mdx": __fd_glob_2, "easify-biometric.de.mdx": __fd_glob_3, "easify-biometric.en.mdx": __fd_glob_4, "easify-biometric.fa.mdx": __fd_glob_5, "easify-bluetooth.de.mdx": __fd_glob_6, "easify-bluetooth.en.mdx": __fd_glob_7, "easify-bluetooth.fa.mdx": __fd_glob_8, "easify-camera.de.mdx": __fd_glob_9, "easify-camera.en.mdx": __fd_glob_10, "easify-camera.fa.mdx": __fd_glob_11, "easify-context.de.mdx": __fd_glob_12, "easify-context.en.mdx": __fd_glob_13, "easify-context.fa.mdx": __fd_glob_14, "easify-file.de.mdx": __fd_glob_15, "easify-file.en.mdx": __fd_glob_16, "easify-file.fa.mdx": __fd_glob_17, "easify-fintech.de.mdx": __fd_glob_18, "easify-fintech.en.mdx": __fd_glob_19, "easify-fintech.fa.mdx": __fd_glob_20, "easify-form.de.mdx": __fd_glob_21, "easify-form.en.mdx": __fd_glob_22, "easify-form.fa.mdx": __fd_glob_23, "easify-format.de.mdx": __fd_glob_24, "easify-format.en.mdx": __fd_glob_25, "easify-format.fa.mdx": __fd_glob_26, "easify-haptic.de.mdx": __fd_glob_27, "easify-haptic.en.mdx": __fd_glob_28, "easify-haptic.fa.mdx": __fd_glob_29, "easify-image.de.mdx": __fd_glob_30, "easify-image.en.mdx": __fd_glob_31, "easify-image.fa.mdx": __fd_glob_32, "easify-lifecycle.de.mdx": __fd_glob_33, "easify-lifecycle.en.mdx": __fd_glob_34, "easify-lifecycle.fa.mdx": __fd_glob_35, "easify-location.de.mdx": __fd_glob_36, "easify-location.en.mdx": __fd_glob_37, "easify-location.fa.mdx": __fd_glob_38, "easify-network.de.mdx": __fd_glob_39, "easify-network.en.mdx": __fd_glob_40, "easify-network.fa.mdx": __fd_glob_41, "easify-notification.de.mdx": __fd_glob_42, "easify-notification.en.mdx": __fd_glob_43, "easify-notification.fa.mdx": __fd_glob_44, "easify-permission.de.mdx": __fd_glob_45, "easify-permission.en.mdx": __fd_glob_46, "easify-permission.fa.mdx": __fd_glob_47, "easify-persian.de.mdx": __fd_glob_48, "easify-persian.en.mdx": __fd_glob_49, "easify-persian.fa.mdx": __fd_glob_50, "easify-security.de.mdx": __fd_glob_51, "easify-security.en.mdx": __fd_glob_52, "easify-security.fa.mdx": __fd_glob_53, "easify-sensor.de.mdx": __fd_glob_54, "easify-sensor.en.mdx": __fd_glob_55, "easify-sensor.fa.mdx": __fd_glob_56, "easify-storage.de.mdx": __fd_glob_57, "easify-storage.en.mdx": __fd_glob_58, "easify-storage.fa.mdx": __fd_glob_59, "easify-ui.de.mdx": __fd_glob_60, "easify-ui.en.mdx": __fd_glob_61, "easify-ui.fa.mdx": __fd_glob_62, "easify-validation.de.mdx": __fd_glob_63, "easify-validation.en.mdx": __fd_glob_64, "easify-validation.fa.mdx": __fd_glob_65, "index.de.mdx": __fd_glob_66, "index.en.mdx": __fd_glob_67, "index.fa.mdx": __fd_glob_68, });

export const meta = await create.meta("meta", "content/docs", {});